### ISSUE TITLE
ClassNotFoundException and crashes at opening..

### ISSUE THREAD

**Issue by forlayo** [infinum/android_dbinspector#10] opened 2015-03-02 15:18 UTC
I'm getting one crash when I try to start Db Inspector activity I got a crash, my app uses multidex I'm not sure if occurs because of that but maybe..

```

03-02 16:17:32.062  21356-21356/com.displaynote.solano E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.bla/im.dino.dbinspector.activities.DbInspectorActivity}: java.lang.ClassNotFoundException: Didn't find class "im.dino.dbinspector.activities.DbInspectorActivity" on path: /data/app/com.bla-1.apk
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
            at android.app.ActivityThread.access$700(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:175)
            at android.app.ActivityThread.main(ActivityThread.java:5279)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "im.dino.dbinspector.activities.DbInspectorActivity" on path: /data/app/com.bla-1.apk
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
            at android.app.Instrumentation.newActivity(Instrumentation.java:1071)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
            at android.app.ActivityThread.access$700(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:175)
            at android.app.ActivityThread.main(ActivityThread.java:5279)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)

```

**Comment by reisub** [comment] 2015-03-07 19:40
Hi @forlayo,
thanks for reporting this.

Can you give me more details on how to reproduce it?
Which device, android version, and how are you starting the DbInspectorActivity?

**Comment by reisub** [comment] 2015-04-18 11:01
Closing until we get more info or a way to reproduce it.

**Closed by reisub** 2015-04-18 11:01 UTC

**Comment by kishorebng** [comment] 2019-05-22 19:44
Getting this force  close when include in project
2019-05-22 15:36:25.323 14503-14503/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fitbit.weighttracker, PID: 14503
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.fitbit.weighttracker/im.dino.dbinspector.activities.DbInspectorActivity}: java.lang.ClassNotFoundException: Didn't find class "im.dino.dbinspector.activities.DbInspectorActivity" on path: DexPathList[[zip file "/data/app/com.fitbit.weighttracker-K6um3P7gM1xG8lAR-jIvww==/base.apk"],nativeLibraryDirectories=[/data/app/com.fitbit.weighttracker-K6um3P7gM1xG8lAR-jIvww==/lib/arm64, /system/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3019)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3250)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "im.dino.dbinspector.activities.DbInspectorActivity" on path: DexPathList[[zip file "/data/app/com.fitbit.weighttracker-K6um3P7gM1xG8lAR-jIvww==/base.apk"],nativeLibraryDirectories=[/data/app/com.fitbit.weighttracker-K6um3P7gM1xG8lAR-jIvww==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3007)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3250) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7032) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 16 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.fitbit.weighttracker-K6um3P7gM1xG8lAR-jIvww==/base.apk"],nativeLibraryDirectories=[/data/app/com.fitbit.weighttracker-K6um3P7gM1xG8lAR-jIvww==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 19 more
